//
// TODO: https://docs.aws.amazon.com/lumberyard/latest/userguide/asset-pipeline-developers.html
//
#pragma once
#ifdef _MSC_VER
#	define CPP_HOT_RELOAD_PLATFORM_WINDOWS 1
#	define CPP_HOT_RELOAD_PLATFORM_MAC 0
#else
#	define CPP_HOT_RELOAD_PLATFORM_WINDOWS 0
#	define CPP_HOT_RELOAD_PLATFORM_MAC 1
#endif

#define LUMBERYARD_ROOT								"E:/Amazon/Lumberyard_1.21/"
#define LUMBERYARD_CPP_HOT_RELOAD_DEV				LUMBERYARD_ROOT "dev/"
#define LUMBERYARD_CPP_HOT_RELOAD_THIRDPARTY_DIR	LUMBERYARD_ROOT "3rdParty/"
#define LUMBERYARD_CPP_HOT_RELOAD_GAME_ROOT			LUMBERYARD_CPP_HOT_RELOAD_DEV	    "SamplesProject/"
#define LUMBERYARD_CPP_HOT_RELOAD_GEM_ROOT			LUMBERYARD_CPP_HOT_RELOAD_GAME_ROOT "Gem/"
#define LUMBERYARD_CPP_HOT_RELOAD_GAME_FILES		LUMBERYARD_CPP_HOT_RELOAD_GEM_ROOT  "Code/Source/Game/"
#define LUMBERYARD_CPP_HOT_RELOAD_PATH				LUMBERYARD_CPP_HOT_RELOAD_GEM_ROOT  "Code/CppHotReload/"
#define LUMBERYARD_CPP_HOT_RELOAD_INCLUDE_FILES		LUMBERYARD_CPP_HOT_RELOAD_PATH		"IncludeDirectories.txt"
#define LUMBERYARD_CPP_HOT_RELOAD_BINARIES_PATH		LUMBERYARD_CPP_HOT_RELOAD_PATH		"Binaries/"
//
// Build configuration
//
#ifdef _DEBUG
#	define CPP_HOT_RELOAD_CONFIGURATION "Debug"
#	define CPP_HOT_RELOAD_IS_DEBUG 1
#	define LUMBERYARD_CPP_HOT_RELOAD_LIB_PATH		LUMBERYARD_CPP_HOT_RELOAD_DEV "BinTemp/win_x64_vs2017_debug/"
#else
#	define CPP_HOT_RELOAD_CONFIGURATION "Release"
#	define CPP_HOT_RELOAD_IS_DEBUG 0
#	define LUMBERYARD_CPP_HOT_RELOAD_LIB_PATH		LUMBERYARD_CPP_HOT_RELOAD_DEV "BinTemp/win_x64_vs2017_profile/"
#endif
#if CPP_HOT_RELOAD_PLATFORM_WINDOWS
#	define CPP_HOT_RELOAD_PLATFORM_NAME "Windows"
#	if _WIN64
#		define CPP_HOT_RELOAD_ARCH_NAME "x64"
#	else
#		error "Platform not supported"
#	endif
#elif CPP_HOT_RELOAD_PLATFORM_MAC
#		define CPP_HOT_RELOAD_ARCH_NAME "x86_64"
#endif
//
// Windows Platform
//
#if CPP_HOT_RELOAD_PLATFORM_WINDOWS
#	define CPP_HOT_RELOAD_PCH_NAME "StdAfx"
#	define CPP_HOT_RELOAD_PCH_INCLUDE_NAME CPP_HOT_RELOAD_PCH_NAME ".h"
#	define CPP_HOT_RELOAD_PCH_OPTIONS "/FI\"" CPP_HOT_RELOAD_PCH_INCLUDE_NAME "\" /Yu\"" CPP_HOT_RELOAD_PCH_INCLUDE_NAME "\" /Fp\"" LUMBERYARD_CPP_HOT_RELOAD_LIB_PATH "SamplesProject/Gem/Code/" CPP_HOT_RELOAD_PCH_NAME ".2581533.pch\" /FI\"" LUMBERYARD_CPP_HOT_RELOAD_PATH "CppHotReloadCustomContructors.h\" "
#	if CPP_HOT_RELOAD_IS_DEBUG
#		define CPP_HOT_RELOAD_FORCE_COMPILE_OPTIONS CPP_HOT_RELOAD_PCH_OPTIONS "/bigobj /nologo /W3 /WX- /MP /Gy /GF /Gm- /fp:fast /Zc:wchar_t /Zc:forScope /Gd /Zc:inline /wd4530 /wd4577 /wd4005 /wd4240 /FS /Od /Ob0 /Oy- /RTC1 /GR- /MDd /Z7 /GS "
#		define CPP_HOT_RELOAD_PREPROCESSOR_OPTIONS "/D__LUMBERYARD__ /DPRODUCT_SKU_default /D_WIN32 /D_WIN64 /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D_ENABLE_EXTENDED_ALIGNED_STORAGE /D_DEBUG /DAZ_DEBUG_BUILD /DSCRIPTCANVAS_ERRORS_ENABLED /DEXE_VERSION_INFO_0=1 /DEXE_VERSION_INFO_1=21 /DEXE_VERSION_INFO_2=2 /DEXE_VERSION_INFO_3=0 /DPLATFORM_SUPPORTS_AWS_NATIVE_SDK /DUSE_WINDOWS_DLL_SEMANTICS /D_MT /D_DLL /DLY_METRICS_BUILD_TIME=0 /DUSE_ZSTD "
#	else
#		define CPP_HOT_RELOAD_FORCE_COMPILE_OPTIONS CPP_HOT_RELOAD_PCH_OPTIONS "/bigobj /nologo /W3 /WX- /MP /Gy /GF /Gm- /fp:fast /Zc:wchar_t /Zc:forScope /Gd /Zc:inline /wd4530 /wd4577 /wd4005 /wd4240 /FS /Ox /Ob2 /Ot /Oi /Oy- /GR- /MD /Z7 "
#		define CPP_HOT_RELOAD_PREPROCESSOR_OPTIONS "/D__LUMBERYARD__ /DPRODUCT_SKU_default /D_WIN32 /D_WIN64 /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D_ENABLE_EXTENDED_ALIGNED_STORAGE /D_PROFILE /DPROFILE /DNDEBUG /DAZ_ENABLE_TRACING /DAZ_ENABLE_DEBUG_TOOLS /DSCRIPTCANVAS_ERRORS_ENABLED /DEXE_VERSION_INFO_0=1 /DEXE_VERSION_INFO_1=21 /DEXE_VERSION_INFO_2=2 /DEXE_VERSION_INFO_3=0 /DPLATFORM_SUPPORTS_AWS_NATIVE_SDK /DUSE_WINDOWS_DLL_SEMANTICS /D_MT /D_DLL /DLY_METRICS_BUILD_TIME=0 /DUSE_ZSTD "
#	endif
#	define CPP_HOT_RELOAD_FORCE_LINK_OPTIONS "\"" LUMBERYARD_CPP_HOT_RELOAD_LIB_PATH "SamplesProject/Gem/Code/StdAfx.2581533.obj\" /NOLOGO /MANIFEST /LARGEADDRESSAWARE /INCREMENTAL:NO /MACHINE:X64 /OPT:REF /OPT:ICF /DEBUG "
#   if (_MSC_VER >= 1920)	// VS 2019
#		define CPP_HOT_RELOAD_VS_VAR_ALL "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\""
#   elif (_MSC_VER > 1910)	// VS 2017
#		define CPP_HOT_RELOAD_VS_VAR_ALL "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\""
#	endif
#endif